### ISSUE TITLE
Confusion about periodic activation functions

### ISSUE THREAD

**Issue by TianGao-NJUST** [edmav4/BiPer#1]
Hello，goodwork. Your work gave me some inspiration. But I want to know whether the training phase is more difficult than other binary networks.

**Comment by edmav4** [comment]
Hi Tian, I'm happy this work gives you inspiration :). The training phase
is relatively easy. Depending on your application, you must tune the
frequency and analyze the quantization errors and degradation accuracies.

bests,

Edwin
